use crate::models::{AuditEvent, ConnectorSnapshot, ExporterConfig};

pub fn connector_snapshots() -> Vec<ConnectorSnapshot> {
    vec![
        ConnectorSnapshot {
            id: "conn-psm-emea-01".into(),
            name: "EMEA PSM connector".into(),
            pool: "psm-emea-primary".into(),
            region: "emea".into(),
            target: "CyberArk PSM / privileged sessions".into(),
            auth_mode: "certificate + identity".into(),
            pool_status: "degraded".into(),
            active_sessions: 142,
            saturation_percent: 88,
            auth_failures_24h: 14,
            latency_ms_p95: 412,
            stale_minutes: 9,
            cert_expiry_days: 12,
            otel_export_enabled: true,
            prometheus_job: "cyberark_psm_emea".into(),
            last_sync_minutes: 4,
        },
        ConnectorSnapshot {
            id: "conn-cpm-prod-02".into(),
            name: "Prod CPM connector".into(),
            pool: "cpm-prod-rotation".into(),
            region: "us-east".into(),
            target: "CyberArk CPM / rotation lane".into(),
            auth_mode: "machine identity".into(),
            pool_status: "healthy".into(),
            active_sessions: 66,
            saturation_percent: 51,
            auth_failures_24h: 2,
            latency_ms_p95: 178,
            stale_minutes: 2,
            cert_expiry_days: 74,
            otel_export_enabled: true,
            prometheus_job: "cyberark_cpm_prod".into(),
            last_sync_minutes: 1,
        },
        ConnectorSnapshot {
            id: "conn-vendor-access-03".into(),
            name: "Vendor access relay".into(),
            pool: "vendor-broker-pool".into(),
            region: "us-central".into(),
            target: "Third-party privileged broker".into(),
            auth_mode: "legacy API key".into(),
            pool_status: "critical".into(),
            active_sessions: 27,
            saturation_percent: 96,
            auth_failures_24h: 33,
            latency_ms_p95: 691,
            stale_minutes: 23,
            cert_expiry_days: 0,
            otel_export_enabled: false,
            prometheus_job: "cyberark_vendor_access".into(),
            last_sync_minutes: 16,
        },
        ConnectorSnapshot {
            id: "conn-identity-bridge-04".into(),
            name: "Identity bridge".into(),
            pool: "identity-bridge-pool".into(),
            region: "us-west".into(),
            target: "CyberArk Identity bridge".into(),
            auth_mode: "oidc + certificate".into(),
            pool_status: "healthy".into(),
            active_sessions: 54,
            saturation_percent: 47,
            auth_failures_24h: 1,
            latency_ms_p95: 161,
            stale_minutes: 1,
            cert_expiry_days: 91,
            otel_export_enabled: true,
            prometheus_job: "cyberark_identity_bridge".into(),
            last_sync_minutes: 1,
        },
        ConnectorSnapshot {
            id: "conn-pvwa-latam-05".into(),
            name: "LATAM PVWA gateway".into(),
            pool: "pvwa-latam".into(),
            region: "latam".into(),
            target: "CyberArk PVWA".into(),
            auth_mode: "identity federation".into(),
            pool_status: "watch".into(),
            active_sessions: 79,
            saturation_percent: 69,
            auth_failures_24h: 7,
            latency_ms_p95: 264,
            stale_minutes: 6,
            cert_expiry_days: 31,
            otel_export_enabled: true,
            prometheus_job: "cyberark_pvwa_latam".into(),
            last_sync_minutes: 3,
        },
    ]
}

pub fn exporter_config() -> ExporterConfig {
    ExporterConfig {
        scrape_interval_seconds: 30,
        otel_endpoint: "http://otel-collector.internal:4318/v1/metrics".into(),
        prometheus_namespace: "cyberark_connector".into(),
        alert_targets: vec![
            "pagerduty://security-platform".into(),
            "slack://privileged-access-ops".into(),
        ],
        retention_hours: 168,
    }
}

pub fn audit_log() -> Vec<AuditEvent> {
    vec![
        AuditEvent {
            timestamp: "2026-05-14 10:01:12".into(),
            action: "SCRAPE_STARTED".into(),
            resource: "cyberark_psm_emea".into(),
            result: "success".into(),
            detail: "Exporter started a fresh connector-health scrape against the EMEA PSM lane.".into(),
        },
        AuditEvent {
            timestamp: "2026-05-14 10:01:41".into(),
            action: "POOL_SATURATION_FLAGGED".into(),
            resource: "vendor-broker-pool".into(),
            result: "warning".into(),
            detail: "Active sessions and auth retries crossed the critical threshold for the vendor connector.".into(),
        },
        AuditEvent {
            timestamp: "2026-05-14 10:02:09".into(),
            action: "OTEL_EXPORT_SKIPPED".into(),
            resource: "cyberark_vendor_access".into(),
            result: "failure".into(),
            detail: "Telemetry export was skipped because the connector still uses a legacy API-key lane without OTel wiring.".into(),
        },
        AuditEvent {
            timestamp: "2026-05-14 10:02:44".into(),
            action: "PROMETHEUS_PAYLOAD_EMITTED".into(),
            resource: "cyberark_connector_*".into(),
            result: "success".into(),
            detail: "Connector health, latency, saturation, and auth-failure metrics emitted into Prometheus format.".into(),
        },
        AuditEvent {
            timestamp: "2026-05-14 10:03:17".into(),
            action: "REMEDIATION_RECOMMENDATION".into(),
            resource: "EMEA PSM connector".into(),
            result: "success".into(),
            detail: "Operator recommendation generated: clear saturation, rotate certificate, and reduce auth-failure pressure before the next review window.".into(),
        },
    ]
}
